# Generated by Django 5.2.6 on 2026-01-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('rented_quantity', models.IntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/')),
            ],
        ),
    ]
